---
title: "Kelch PfK7 Selection Coefficient Modeling - MANUSCRIPT"
output: html_document
date: "2023-03-16"
---

```{r setup, include=FALSE}
library(lme4)
library(nlme)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(scales)
library(tidyverse)
library(cowplot)
library(tabulizer)
library(RColorBrewer)
library(tidyverse) # ggplot2, dplyr, tidyr, readr, purrr, tibble
library(rnaturalearth)
library(rnaturalearthdata)
library(sf) #see ubuntu issues here: https://rtask.thinkr.fr/installation-of-r-4-0-on-ubuntu-20-04-lts-and-tips-for-spatial-packages/
library(ggspatial)
library(scatterpie)
library(scales)
library (ggforce)
library (ggmap)
library(rstan)
library(gt)
## install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

# Load data
```{r}
#load data
pfk7_data <- read.table("data/data-derived/pfk7_data_adj.txt") %>% filter(Locus != "other_PfK13")
#set the limit of number of observations
numofobs <- 2

fileLocManuscript_pfK7 <- "figures/"
```

# Bayesian GMM with slopes and intercepts
```{r}
# Have a read through rstanarm vignettes and guides on how it works in comparison to lme4

# ---- Model for c580y -----
c580y_stanmod <- rstanarm::stan_glmer(
  lrsmed ~ adj_year + (1 + adj_year | District),
  data = pfk7_data %>% 
    filter(Locus == "C580Y", nobs > numofobs),
  weights = wt_med, 
  adapt_delta = 0.9975
)

vals <- summary(c580y_stanmod$stanfit)$summary[,1]
vals <- vals[grep("^b", names(vals))]
ranef_c580y_stanmod <- data.frame("Intercepts" = vals[seq(1, length(vals), 2)],
           "Slopes" = vals[seq(2, length(vals), 2)])
ranef_c580y_stanmod$mutation <- rep("C580Y", dim(ranef_c580y_stanmod)[1])

# ---- Model for r539t -----
r539t_stanmod <- rstanarm::stan_glmer(
  lrsmed ~ adj_year + (1 + adj_year | District),
  data = pfk7_data %>% filter(Locus == "R539T", nobs > numofobs),
  weights = wt_med, 
  adapt_delta = 0.9975
)

vals <- summary(r539t_stanmod$stanfit)$summary[,1]
vals <- vals[grep("^b", names(vals))]
ranef_r539t_stanmod <- data.frame("Intercepts" = vals[seq(1, length(vals), 2)],
           "Slopes" = vals[seq(2, length(vals), 2)])
ranef_r539t_stanmod$mutation <- rep("R539T", dim(ranef_r539t_stanmod)[1])

# ---- Model for combined kelch -----
all_kelch_stanmod <- rstanarm::stan_glmer(
  lrsmed ~ adj_year + (1 + adj_year | District),
  data = pfk7_data %>% filter(Locus == "PfK13", nobs > numofobs),
  weights = wt_med, 
  adapt_delta = 0.9975
)

vals <- summary(all_kelch_stanmod$stanfit)$summary[,1]
vals <- vals[grep("^b", names(vals))]
ranef_all_kelch_stanmod<- data.frame("Intercepts" = vals[seq(1, length(vals), 2)],
           "Slopes" = vals[seq(2, length(vals), 2)])
ranef_all_kelch_stanmod$mutation <- rep("PfK13", dim(ranef_all_kelch_stanmod)[1])

ranef_stanmod <- rbind(ranef_c580y_stanmod, ranef_r539t_stanmod, ranef_all_kelch_stanmod)
ranef_stanmod$site <- str_replace_all(rownames(ranef_stanmod), "\\[|\\]", "")
ranef_stanmod$site <- str_replace_all(ranef_stanmod$site, "\\s*\\([^\\)]+\\)", "")
ranef_stanmod$site <- str_remove(ranef_stanmod$site, "b District:")
ranef_stanmod$site <- str_remove(ranef_stanmod$site, "1")
``` 

## Posterior of the model
```{r}
#  get model predictions for plotting
pfk7_data$predict_stan <- NA

pfk7_data$predict_stan[is.finite(pfk7_data$lrsmed) & pfk7_data$Locus == "C580Y" & pfk7_data$nobs > numofobs] <-  rstanarm::posterior_predict(c580y_stanmod, type = "response") %>% colMeans
pfk7_data$predict_stan[is.finite(pfk7_data$lrsmed) & pfk7_data$Locus == "R539T" & pfk7_data$nobs > numofobs] <-  rstanarm::posterior_predict(r539t_stanmod, type = "response") %>% colMeans
pfk7_data$predict_stan[is.finite(pfk7_data$lrsmed) & pfk7_data$Locus == "PfK13" & pfk7_data$nobs > numofobs] <-  rstanarm::posterior_predict(all_kelch_stanmod, type = "response") %>% colMeans
```

## Confidence interval
```{r}
#  get model predictions for plotting
pfk7_data$conf.low <- NA
pfk7_data$conf.high <- NA

c580y_conf <- rstanarm::posterior_predict(c580y_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))
r539t_conf <- rstanarm::posterior_predict(r539t_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))
all_kelch_conf <- rstanarm::posterior_predict(all_kelch_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))

# here just add predictions  for the c469Y rows
pfk7_data$conf.low[is.finite(pfk7_data$lrsmed) & pfk7_data$Locus == "C580Y" & pfk7_data$nobs > numofobs] <- c580y_conf[1,]
pfk7_data$conf.low[is.finite(pfk7_data$lrsmed) & pfk7_data$Locus == "R539T" & pfk7_data$nobs > numofobs] <- r539t_conf[1,]
pfk7_data$conf.low[is.finite(pfk7_data$lrsmed) & pfk7_data$Locus == "PfK13" & pfk7_data$nobs > numofobs] <- all_kelch_conf[1,]

pfk7_data$conf.high[is.finite(pfk7_data$lrsmed) & pfk7_data$Locus == "C580Y" & pfk7_data$nobs > numofobs] <- c580y_conf[2,]
pfk7_data$conf.high[is.finite(pfk7_data$lrsmed) & pfk7_data$Locus == "R539T" & pfk7_data$nobs > numofobs] <- r539t_conf[2,]
pfk7_data$conf.high[is.finite(pfk7_data$lrsmed) & pfk7_data$Locus == "PfK13" & pfk7_data$nobs > numofobs] <- all_kelch_conf[2,]
```

## Prevalence scale
```{r}
# Plot the predictions in each site with only Bayesian
#convert to prevalence scale
pfk7_data$predict_stan_prev <- NA

pfk7_data$predict_stan_prev <- exp(pfk7_data$predict_stan)*100/(1+exp(pfk7_data$predict_stan))
pfk7_data$conf.high_prev <- exp(pfk7_data$conf.high)*100/(1+exp(pfk7_data$conf.high))
pfk7_data$conf.low_prev <- exp(pfk7_data$conf.low)*100/(1+exp(pfk7_data$conf.low))
```

# SFigure6: Plot prevalence for all mutations
## Preprocessing
```{r}
prev_df2 <- pfk7_data %>% filter(nobs > numofobs)
prev_df <- rbind(prev_df2, pfk7_data %>% filter(District == "Bago" | District == "Bac Lieu" | District == "Mandalay" | District == "Ninh Thuan")) ## added these sites to show general prevalence across SE Asia
```

## Supplement Plot
```{r}
prev_plot <- prev_df2  %>%
  ggplot(aes(year, prev*100, group = Locus, color = Locus)) +
  geom_point(aes(size = n, group = Locus, color = Locus)) +
  facet_wrap(~country + District) +
  labs(shape="Mutations", size = "Sample Size") +
  theme_bw() +
  geom_line(data = prev_df %>% filter(nobs > numofobs, is.finite(lrsmed)), aes(year, predict_stan_prev, color = Locus, group = Locus), size = 1) +
  geom_ribbon(data = prev_df %>% filter(nobs > numofobs, is.finite(lrsmed)), aes(ymin = conf.low_prev, ymax = conf.high_prev, color = Locus, fill = Locus), alpha = 0.2,  show.legend = FALSE) +
  scale_color_manual(
    values = c("#56B4E9", "#E69F00", "#009E73"),
    name = "Mutations",
    labels = c("580Y", "PfK13", "539T")
  ) +
  scale_fill_manual(values = c("#56B4E9", "#E69F00", "#009E73")) + 
  ylab("Prevalence") +
  xlab("Year") +
  ylim(-1, 101)+
  ggpubr::theme_pubclean(base_size = 12)+
  theme(
    axis.line = element_line(),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 12),
    strip.text.x = element_text(size = 12),
    legend.title = element_text(size = 12),
    legend.position = "right",
    legend.box = "vertial"
  )
```

## Saving plots
```{r}
ggsave(
  paste0(fileLocManuscript_pfK7, "/supplement/Figure6-SEAsiaPrevalence/ADJUSTED_SEAsia_posterior_prevalence.png"),
  prev_plot,
  width = 8,
  height = 8,
  dpi = 700
)
ggsave(
  paste0(fileLocManuscript_pfK7, "/supplement/Figure6-SEAsiaPrevalence/ADJUSTED_SEAsia_posterior_prevalence.pdf"),
  prev_plot,
  width = 8,
  height = 8,
  dpi = 700
)
```

# Plot selection coefficient 
## Preprocessing
```{r}
# Plot the effect sizes
stan_eff <- as.data.frame(t(data.frame(c580y_stanmod$stan_summary[2, c("2.5%", "50%","97.5%")]))) %>%
mutate(method = "Bayesian (Intercept + Slope)") %>%
setNames(c("conf.low", "estimate", "conf.high", "method"))

effect_size <- stan_eff %>% mutate(mutation = "C580Y")

stan_eff <- as.data.frame(t(data.frame(r539t_stanmod$stan_summary[2, c("2.5%", "50%","97.5%")]))) %>%
mutate(method = "Bayesian (Intercept + Slope)") %>%
setNames(c("conf.low", "estimate", "conf.high", "method"))

effect_size <- rbind(effect_size, stan_eff %>% mutate(mutation = "R539T"))

stan_eff <- as.data.frame(t(data.frame(all_kelch_stanmod$stan_summary[2, c("2.5%", "50%","97.5%")]))) %>%
mutate(method = "Bayesian (Intercept + Slope)") %>%
setNames(c("conf.low", "estimate", "conf.high", "method"))

effect_size <- rbind(effect_size, stan_eff %>% mutate(mutation = "PfK13"))

#confidence interval per site and mutation
stan_eff_c580y <- as.data.frame(c580y_stanmod$stan_summary[grep("year District", rownames(c580y_stanmod$stan_summary)),]) %>%
  select(c("2.5%","97.5%")) %>% 
  setNames(c("conf.low", "conf.high")) %>% 
  slice(1:(n()-1))
stan_eff_r539t <- as.data.frame(r539t_stanmod$stan_summary[grep("year District", rownames(r539t_stanmod$stan_summary)),]) %>%
  select(c("2.5%","97.5%")) %>% 
  setNames(c("conf.low", "conf.high")) %>% 
  slice(1:(n()-1))
stan_eff_all_kelch <- as.data.frame(all_kelch_stanmod$stan_summary[grep("year District", rownames(all_kelch_stanmod$stan_summary)),]) %>% 
  select(c("2.5%","97.5%")) %>% 
  setNames(c("conf.low", "conf.high")) %>%
  slice(1:(n()-1))

coef_c580y <- ranef(c580y_stanmod)$District %>% 
  mutate(District = rownames(ranef(c580y_stanmod)$District), 
         mutation = "C580Y", 
         estimate = ranef(c580y_stanmod)$District$adj_year, 
         conf.low = stan_eff_c580y$conf.low, 
         conf.high = stan_eff_c580y$conf.high) %>% 
  select(conf.low, estimate, conf.high, mutation, District) %>% 
  remove_rownames()

coef_r539t <- ranef(r539t_stanmod)$District %>% 
  mutate(District = rownames(ranef(r539t_stanmod)$District), 
         mutation = "R539T", 
         estimate = ranef(r539t_stanmod)$District$adj_year, 
         conf.low = stan_eff_r539t$conf.low, 
         conf.high = stan_eff_r539t$conf.high) %>% 
  select(conf.low, estimate, conf.high, mutation, District) %>% 
  remove_rownames()

coef_all_kelch <- ranef(all_kelch_stanmod)$District %>% 
  mutate(District = rownames(ranef(all_kelch_stanmod)$District), 
         mutation = "PfK13", 
         estimate = ranef(all_kelch_stanmod)$District$adj_year, 
         conf.low = stan_eff_all_kelch$conf.low, 
         conf.high = stan_eff_all_kelch$conf.high) %>% 
  select(conf.low, estimate, conf.high, mutation, District) %>% 
  remove_rownames()

selec_coef <- rbind(coef_c580y, coef_r539t, coef_all_kelch)

# plot the effect sizes for the mutation
effect_size_bay <- effect_size %>% 
  filter(method == "Bayesian (Intercept + Slope)") %>% 
  mutate(District = "Southeast Asia") %>% 
  select(conf.low, estimate, conf.high, mutation, District)

selec_coef$estimate[selec_coef$mutation == "C580Y"] <- selec_coef$estimate[selec_coef$mutation == "C580Y"] + effect_size_bay$estimate[effect_size_bay$mutation == "C580Y"]
selec_coef$estimate[selec_coef$mutation == "R539T"] <- selec_coef$estimate[selec_coef$mutation == "R539T"] + effect_size_bay$estimate[effect_size_bay$mutation == "R539T"]
selec_coef$estimate[selec_coef$mutation == "PfK13"] <- selec_coef$estimate[selec_coef$mutation == "PfK13"] + effect_size_bay$estimate[effect_size_bay$mutation == "PfK13"]

selec_coef$conf.low[selec_coef$mutation == "C580Y"] <- selec_coef$conf.low[selec_coef$mutation == "C580Y"] + effect_size_bay$conf.low[effect_size_bay$mutation == "C580Y"]
selec_coef$conf.low[selec_coef$mutation == "R539T"] <- selec_coef$conf.low[selec_coef$mutation == "R539T"] + effect_size_bay$conf.low[effect_size_bay$mutation == "R539T"]
selec_coef$conf.low[selec_coef$mutation == "PfK13"] <- selec_coef$conf.low[selec_coef$mutation == "PfK13"] + effect_size_bay$conf.low[effect_size_bay$mutation == "PfK13"]

selec_coef$conf.high[selec_coef$mutation == "C580Y"] <- selec_coef$conf.high[selec_coef$mutation == "C580Y"] + effect_size_bay$conf.high[effect_size_bay$mutation == "C580Y"]
selec_coef$conf.high[selec_coef$mutation == "R539T"] <- selec_coef$conf.high[selec_coef$mutation == "R539T"] + effect_size_bay$conf.high[effect_size_bay$mutation == "R539T"]
selec_coef$conf.high[selec_coef$mutation == "PfK13"] <- selec_coef$conf.high[selec_coef$mutation == "PfK13"] + effect_size_bay$conf.high[effect_size_bay$mutation == "PfK13"]

effect_size_bay$s <- 18
effect_size_bay$sizes <- 1
selec_coef$s <- 19
selec_coef$sizes <- 0.5

stan_eff_bay_overall <- effect_size_bay %>% 
  mutate(method = "Baysian") %>% 
  relocate(District, conf.low, estimate, conf.high, method, mutation, s, sizes)
rownames(stan_eff_bay_overall) <- NULL

# selec_coef_bay <- selec_coef %>% mutate(method = "Baysian") %>% relocate(District, conf.low, estimate, conf.high, method, mutation, s, sizes)

effect_size_bay <- rbind(effect_size_bay, selec_coef)
effect_size_bay <- effect_size_bay %>% 
  group_by(mutation) %>% 
  arrange(District)

effect_size_bay <- effect_size_bay %>% 
  mutate(mutation = replace(mutation, mutation == "C580Y", "580Y"), mutation = replace(mutation, mutation == "R539T", "539T")) 
```

## Figure3: Plot
```{r}
selection_coef_bay <- ggplot() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_pointrange(data = effect_size_bay, 
                  aes(x = estimate, y = mutation, xmin = conf.low, xmax = conf.high, color = District),
                  position=position_dodge(width = 0.6), shape = effect_size_bay$s, size = effect_size_bay$sizes) +
  scale_y_discrete(labels = c("539T", "580Y", "PfK13")) +
  ylab("Mutation") +
  xlab("Selection Coefficient") +
  xlim(-2.5,4) +
    scale_color_manual(values=c("#4477AA",
                              "#66CCEE",
                              "#228833",
                              "#CCBB44",
                              "#EE6677",
                              "#AA3377",
                              "#DDAA33",
                              "#004488",
                              "#CC3311",
                              "#44AA99",
                              "#EE99AA",
                              "#EE7733",
                              "black")) +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    axis.line = element_line(),
    legend.position = "right",
    plot.title = element_text(hjust = 0.5, size = 20),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    legend.text = element_text(size = 10)
  )

effect_size_bay2 <- effect_size_bay %>% 
  relocate(District, mutation) %>% 
  select(!(s:sizes)) %>% 
  mutate(conf.low = round(conf.low, 3), conf.high = round(conf.high, 3), estimate = round(estimate, 3))
```

### Saving plots
```{r}
ggsave(
  paste0(fileLocManuscript_pfK7, "/Figure3-SelectionCeof/ADJUSTED_Figure3_SEAsia_Effectsize.png"),
  selection_coef_bay,
  width = 8,
  height = 5,
  dpi = 700
)
ggsave(
  paste0(fileLocManuscript_pfK7, "/Figure3-SelectionCeof/ADJUSTED_Figure3_SEAsia_Effectsize.pdf"),
  selection_coef_bay,
  width = 8,
  height = 5,
  dpi = 700
)
write.csv(
  effect_size_bay2,
  paste0(fileLocManuscript_pfK7, "/Figure3-SelectionCeof/ADJUSTED_SEAsia_selectioncoefficients.csv"),
  row.names = F,
  quote = F
)
```


### Statistical analysis of selection coefficients
```{r}
selec_ceof_stats <- data.frame(matrix(ncol = 5, nrow = 3))
min_580Y <- min(effect_size_bay %>% filter(mutation == "580Y" & District != "Southeast Asia") %>% pull(estimate))
max_580Y <- max(effect_size_bay %>% filter(mutation == "580Y" & District != "Southeast Asia") %>% pull(estimate))
selec_ceof_stats[1, ] <- cbind("580Y", 
                               round(min_580Y, 3), 
                               effect_size_bay[which(effect_size_bay$estimate == min_580Y),][5], 
                               round(max_580Y, 3), 
                               effect_size_bay[which(effect_size_bay$estimate == max_580Y),][5])

min_539T <- min(effect_size_bay %>% filter(mutation == "539T" & District != "Southeast Asia") %>% pull(estimate))
max_539T <- max(effect_size_bay %>% filter(mutation == "539T" & District != "Southeast Asia") %>% pull(estimate))
selec_ceof_stats[2, ] <- cbind("539T", 
                               round(min_539T, 3),
                               effect_size_bay[which(effect_size_bay$estimate == min_539T),][5], 
                               round(max_539T, 3), 
                               effect_size_bay[which(effect_size_bay$estimate == max_539T),][5])

min_PfK13 <- min(effect_size_bay %>% filter(mutation == "PfK13" & District != "Southeast Asia") %>% pull(estimate))
max_PfK13 <- max(effect_size_bay %>% filter(mutation == "PfK13" & District != "Southeast Asia") %>% pull(estimate))
selec_ceof_stats[3, ] <- cbind("PfK13", 
                               round(min_PfK13, 3), 
                               effect_size_bay[which(effect_size_bay$estimate == min_PfK13),][5], 
                               round(max_PfK13, 3), 
                               effect_size_bay[which(effect_size_bay$estimate == max_PfK13),][5])

colnames(selec_ceof_stats) <- c("Mutation", "Min", "District", "Max", "District")
write.csv(
  selec_ceof_stats,
  paste0(fileLocManuscript_pfK7, "/Figure3-SelectionCeof/ADJUSTED_SEAsia_selectioncoefficients_stats.csv"),
  row.names = F,
  quote = F
)
```

