---
title: "Kelch PfK7 Prediction"
output: html_document
date: "2023-03-16"
---

```{r setup, include=FALSE}
library(lme4)
library(nlme)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(scales)
library(tidyverse)
library(cowplot)
library(tabulizer)
library(RColorBrewer)
library(tidyverse) # ggplot2, dplyr, tidyr, readr, purrr, tibble
library(rnaturalearth)
library(rnaturalearthdata)
library(sf) #see ubuntu issues here: https://rtask.thinkr.fr/installation-of-r-4-0-on-ubuntu-20-04-lts-and-tips-for-spatial-packages/
library(ggspatial)
library(scatterpie)
library(scales)
library (ggforce)
library (ggmap)
library(rstan)
library(gt)
## install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))

```

#load data
```{r}
#load data
pfk7_data <- read.table("data/data-derived/pfk7_data.txt")
#set the limit of number of observations
numofobs <- 2

pfk7_data <- pfk7_data %>%
  group_by(District) %>%
  mutate(min_year_c580y = min(year[c580y>0]), min_year_r539t = min(year[r539t>0]), min_year_all_kelch = min(year[all_kelch>0])) %>%
  ungroup 
```

# Bayesian stan model with slopes and intercepts
```{r}
# Have a read through rstanarm vignettes and guides on how it works in comparison to lme4
# ---- Model for c580y -----
c580y_stanmod <- rstanarm::stan_glmer(
  lrsmed_580y ~ adj_year + (1 + adj_year | District),
  data = pfk7_data %>% filter(nobs_c580y > numofobs),
  weights = wt_med_580y, adapt_delta = 0.9975
)

vals <- summary(c580y_stanmod$stanfit)$summary[,1]
vals <- vals[grep("^b", names(vals))]
ranef_c580y_stanmod <- data.frame("Intercepts" = vals[seq(1, length(vals), 2)],
           "Slopes" = vals[seq(2, length(vals), 2)])
ranef_c580y_stanmod$mutation <- rep("c580y", dim(ranef_c580y_stanmod)[1])

# ---- Model for r539t -----

r539t_stanmod <- rstanarm::stan_glmer(
  lrsmed_539t ~ adj_year + (1 + adj_year | District),
  data = pfk7_data %>% filter(nobs_r539t > numofobs),
  weights = wt_med_539t, adapt_delta = 0.9975
)

vals <- summary(r539t_stanmod$stanfit)$summary[,1]
vals <- vals[grep("^b", names(vals))]
ranef_r539t_stanmod <- data.frame("Intercepts" = vals[seq(1, length(vals), 2)],
           "Slopes" = vals[seq(2, length(vals), 2)])
ranef_r539t_stanmod$mutation <- rep("r539t", dim(ranef_r539t_stanmod)[1])

# ---- Model for combined kelch -----

all_kelch_stanmod <- rstanarm::stan_glmer(
  lrsmed_all_kelch ~ adj_year + (1 + adj_year | District),
  data = pfk7_data %>% filter(nobs_kelch > numofobs),
  weights = wt_med_all_kelch, adapt_delta = 0.9975
)


vals <- summary(all_kelch_stanmod$stanfit)$summary[,1]
vals <- vals[grep("^b", names(vals))]
ranef_all_kelch_stanmod<- data.frame("Intercepts" = vals[seq(1, length(vals), 2)],
           "Slopes" = vals[seq(2, length(vals), 2)])
ranef_all_kelch_stanmod$mutation <- rep("all_kelch", dim(ranef_all_kelch_stanmod)[1])

ranef_stanmod <- rbind(ranef_c580y_stanmod, ranef_all_kelch_stanmod, ranef_r539t_stanmod)
ranef_stanmod$site <- str_replace_all(rownames(ranef_stanmod), "\\[|\\]", "")
ranef_stanmod$site <- str_replace_all(ranef_stanmod$site, "\\s*\\([^\\)]+\\)", "")
ranef_stanmod$site <- str_remove(ranef_stanmod$site, "b District:")
ranef_stanmod$site <- str_remove(ranef_stanmod$site, "1")


``` 

## PREDICTIONS 
```{r}
pred_year <- 2
#------ Model prediction for C580Y ------
c580y_pred <- rstanarm::stan_glmer(
  lrsmed_580y ~ adj_year + (1 + adj_year | District),
  data = pfk7_data %>% filter(nobs_c580y > numofobs, year >= min_year_c580y & year <= min_year_c580y + pred_year),
  weights = wt_med_580y, adapt_delta = 0.9975
)

# forecasting
new_data <- pfk7_data %>%
  filter(nobs_c580y > numofobs, is.finite(pfk7_data$lrsmed_580y)) %>% # this is for c469Y model 
  mutate(Locus = "C580Y") %>%
  group_by(country, District, Locus) %>% # we group by the District and Locus 
  complete(year = seq(min(min_year_c580y)+ pred_year, 2023, 1)) %>% # this creates all the year values up to 2023
  #mutate(adj_year = year - min_year_c580y) %>%
  select(adj_year,year, country, min_year_c580y, District, Locus) %>% # select just the columns needed for the model
  mutate(min_year_c580y = replace(min_year_c580y, is.na(min_year_c580y), 0))

new_data <- new_data %>%
  group_by(country, District, Locus) %>%
  mutate(adj_year = year - max(min_year_c580y), min_year = min_year_c580y)

predictions <- rstanarm::posterior_predict(c580y_pred, type = "response", newdata = new_data) %>% colMeans
new_data$predict <- predictions

df_predict <- new_data

#------ Model prediction for R539T ------

r539t_pred <- rstanarm::stan_glmer(
  lrsmed_539t ~ adj_year + (1 + adj_year | District),
  data = pfk7_data %>% filter(nobs_r539t > numofobs, year >= min_year_r539t & year <= min_year_r539t + pred_year),
  weights = wt_med_539t, adapt_delta = 0.9975
)

# forecasting
new_data <- pfk7_data %>%
  filter(nobs_r539t > numofobs, is.finite(pfk7_data$lrsmed_539t)) %>% # this is for r539t model 
  mutate(Locus = "R539T") %>%
  group_by(country, District, Locus) %>%  # we group by the District and Locus 
  complete(year = seq(min(min_year_r539t)+ pred_year, 2023, 1)) %>% # this creates all the year values up to 2023
  #mutate(adj_year = year - min_year_c580y) %>%
  select(adj_year,year, country, min_year_r539t, District, Locus) %>% # select just the columns needed for the model
  mutate(min_year_r539t = replace(min_year_r539t, is.na(min_year_r539t), 0))

new_data <- new_data %>%
  group_by(country, District, Locus) %>%
  mutate(adj_year = year - max(min_year_r539t), min_year = min_year_r539t)

predictions <- rstanarm::posterior_predict(r539t_pred, type = "response", newdata = new_data) %>% colMeans
new_data$predict <- predictions

df_predict <- rbind(df_predict, new_data)

#------ Model prediction for combined PfK13 mutations ------

all_kelch_pred <- rstanarm::stan_glmer(
  lrsmed_all_kelch ~ adj_year + (1 + adj_year | District),
  data = pfk7_data %>% filter(nobs_kelch > numofobs, year >= min_year_all_kelch & year <= min_year_all_kelch + pred_year),
  weights = wt_med_580y, adapt_delta = 0.9975
)

# forecasting
new_data <- pfk7_data %>%
  filter(nobs_kelch > numofobs, is.finite(pfk7_data$lrsmed_all_kelch)) %>% # this is for c469Y model 
  mutate(Locus = "all_kelch") %>%
  group_by(country, District, Locus) %>% # we group by the District and Locus 
  complete(year = seq(min(min_year_all_kelch)+ pred_year, 2023, 1))%>% # this creates all the year values up to 2023
  #mutate(adj_year = year - min_year_c580y) %>%
  select(adj_year,year, country, min_year_all_kelch, District, Locus) %>% # select just the columns needed for the model
  mutate(min_year_all_kelch = replace(min_year_all_kelch, is.na(min_year_all_kelch), 0))

new_data <- new_data %>%
  group_by(country, District, Locus) %>%
  mutate(adj_year = year - max(min_year_all_kelch), min_year = min_year_all_kelch)

predictions <- rstanarm::posterior_predict(all_kelch_pred, type = "response", newdata = new_data) %>% colMeans
new_data$predict <- predictions

df_predict <- rbind(df_predict, new_data)

```

#get model predictions
```{r}
#  get model predictions for plotting
pfk7_data$predict_stan_c580y <- NA
pfk7_data$predict_stan_r539t <- NA
pfk7_data$predict_stan_all_kelch <- NA

pfk7_data$predict_stan_c580y[is.finite(pfk7_data$lrsmed_580y) & pfk7_data$nobs_c580y > numofobs] <-  rstanarm::posterior_predict(c580y_stanmod, type = "response") %>% colMeans
pfk7_data$predict_stan_r539t[is.finite(pfk7_data$lrsmed_539t) & pfk7_data$nobs_r539t > numofobs] <-  rstanarm::posterior_predict(r539t_stanmod, type = "response") %>% colMeans
pfk7_data$predict_stan_all_kelch[is.finite(pfk7_data$lrsmed_all_kelch) & pfk7_data$nobs_kelch > numofobs] <-  rstanarm::posterior_predict(all_kelch_stanmod, type = "response") %>% colMeans
```


## PLOT FOR ONLY BAYSIAN PREDICTION WITH CONF INTERVAL
```{r}
#  get model predictions for plotting
pfk7_data$conf.low_c580y <- NA
pfk7_data$conf.high_c580y <- NA
pfk7_data$conf.low_r539t <- NA
pfk7_data$conf.high_r539t <- NA
pfk7_data$conf.low_all_kelch <- NA
pfk7_data$conf.high_all_kelch <- NA

c580y_conf <- rstanarm::posterior_predict(c580y_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))
r539t_conf <- rstanarm::posterior_predict(r539t_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))
all_kelch_conf <- rstanarm::posterior_predict(all_kelch_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))

# here just add predictions  for the c469Y rows
pfk7_data$conf.low_c580y[is.finite(pfk7_data$lrsmed_580y) & pfk7_data$nobs_c580y > numofobs] <- c580y_conf[1,]
pfk7_data$conf.low_r539t[is.finite(pfk7_data$lrsmed_539t) & pfk7_data$nobs_r539t > numofobs] <- r539t_conf[1,]
pfk7_data$conf.low_all_kelch[is.finite(pfk7_data$lrsmed_all_kelch) & pfk7_data$nobs_kelch > numofobs] <- all_kelch_conf[1,]

pfk7_data$conf.high_c580y[is.finite(pfk7_data$lrsmed_580y) & pfk7_data$nobs_c580y > numofobs] <- c580y_conf[2,]
pfk7_data$conf.high_r539t[is.finite(pfk7_data$lrsmed_539t) & pfk7_data$nobs_r539t > numofobs] <- r539t_conf[2,]
pfk7_data$conf.high_all_kelch[is.finite(pfk7_data$lrsmed_all_kelch) & pfk7_data$nobs_kelch > numofobs] <- all_kelch_conf[2,]
```


#get model predictions
```{r}
# Plot the predictions in each site with only Bayesian
#convert to prevalence scale
#  get model predictions for plotting
pfk7_data$predict_stan_c580y <- NA
pfk7_data$predict_stan_r539t <- NA
pfk7_data$predict_stan_all_kelch <- NA

pfk7_data$predict_stan_c580y[is.finite(pfk7_data$lrsmed_580y) & pfk7_data$nobs_c580y > numofobs] <-  rstanarm::posterior_predict(c580y_stanmod, type = "response") %>% colMeans
pfk7_data$predict_stan_r539t[is.finite(pfk7_data$lrsmed_539t) & pfk7_data$nobs_r539t > numofobs] <-  rstanarm::posterior_predict(r539t_stanmod, type = "response") %>% colMeans
pfk7_data$predict_stan_all_kelch[is.finite(pfk7_data$lrsmed_all_kelch) & pfk7_data$nobs_kelch > numofobs] <-  rstanarm::posterior_predict(all_kelch_stanmod, type = "response") %>% colMeans

pfk7_data$predict_stan_prev_c580y <- exp(pfk7_data$predict_stan_c580y)*100/(1+exp(pfk7_data$predict_stan_c580y))
pfk7_data$predict_stan_prev_r539t <- exp(pfk7_data$predict_stan_r539t)*100/(1+exp(pfk7_data$predict_stan_r539t))
pfk7_data$predict_stan_prev_all_kelch <- exp(pfk7_data$predict_stan_all_kelch)*100/(1+exp(pfk7_data$predict_stan_all_kelch))

pfk7_data$conf.high_prev_c580y <- exp(pfk7_data$conf.high_c580y)*100/(1+exp(pfk7_data$conf.high_c580y))
pfk7_data$conf.high_prev_r539t <- exp(pfk7_data$conf.high_r539t)*100/(1+exp(pfk7_data$conf.high_r539t))
pfk7_data$conf.high_prev_all_kelch <- exp(pfk7_data$conf.high_all_kelch)*100/(1+exp(pfk7_data$conf.high_all_kelch))

pfk7_data$conf.low_prev_c580y <- exp(pfk7_data$conf.low_c580y)*100/(1+exp(pfk7_data$conf.low_c580y))
pfk7_data$conf.low_prev_r539t <- exp(pfk7_data$conf.low_r539t)*100/(1+exp(pfk7_data$conf.low_r539t))
pfk7_data$conf.low_prev_all_kelch <- exp(pfk7_data$conf.low_all_kelch)*100/(1+exp(pfk7_data$conf.low_all_kelch))

d1 <- pfk7_data %>% select(country, District, year, c580y, n, nobs_c580y, lrsmed_580y, prev_580y, predict_stan_prev_c580y, conf.low_prev_c580y, conf.high_prev_c580y) %>% mutate(Locus = "C580Y")
colnames(d1) <- c("country", "District", "year", "x", "n", "nobs", "lrsmed", "prev", "predict_stan_prev", "conf.low_prev", "conf.high_prev", "Locus")
d2 <- pfk7_data %>% select(country, District, year, r539t, n, nobs_r539t, lrsmed_539t, prev_539t, predict_stan_prev_r539t, conf.low_prev_r539t, conf.high_prev_r539t) %>% mutate(Locus = "R539T")
colnames(d2) <- c("country", "District", "year", "x", "n", "nobs", "lrsmed", "prev", "predict_stan_prev", "conf.low_prev", "conf.high_prev", "Locus")
d3 <- pfk7_data %>% select(country, District, year, all_kelch, n, nobs_kelch, lrsmed_all_kelch, prev_all_kelch, predict_stan_prev_all_kelch, conf.low_prev_all_kelch, conf.high_prev_all_kelch) %>% mutate(Locus = "combined PfK13")
colnames(d3) <- c("country", "District", "year", "x", "n", "nobs", "lrsmed", "prev", "predict_stan_prev", "conf.low_prev", "conf.high_prev", "Locus")
prev_df <- rbind(d1, d2, d3)
```

#Plotting
#Prediction plot with points
```{r}
ex <- pfk7_data %>% filter(is.finite(lrsmed_580y), nobs_c580y > numofobs, year >= min_year_c580y) %>% mutate(pt_color = case_when (year>min_year_c580y+ pred_year ~ "#55C667FF", year <= min_year_c580y+ pred_year ~ "#DCE319FF"))
df_pred <- df_predict %>% filter(District %in% unique(ex$District), year >= min_year +  pred_year) 
## PLOT FOR C580Y
prev_c580y_plot <- 
  ggplot() +
  geom_line(data=ex %>% mutate(N = n+c580y), aes(year, predict_stan_prev_c580y, color = "true")) + 
  geom_line(data=df_pred %>% filter(Locus == "C580Y"), aes(year, exp(predict)*100/(1+exp(predict)) , color = "predicted")) +
  geom_vline(data=ex, aes(xintercept= min_year_c580y + pred_year), linetype = "dashed") +
  geom_point(data = ex, aes(x=year, y=prev_580y*100), color = ex$pt_color) +
  ggtitle("C580Y") +
  labs(shape="Mutations", size = "Sample Size") +
  theme_bw() +
  facet_wrap(~country + District) +
  #scale_y_log10() +
  scale_color_manual(values=c("#440154FF", "#33638DFF")) + 
  #scale_fill_manual(values=c("grey", "#0072B2", "red", "green")) + 
  ylab("Prevalence") +
  xlab("Year") +
  ggpubr::theme_pubclean(base_size = 12) +
  theme(axis.line = element_line(), axis.text = element_text(size = 8), axis.title=element_text(size=12), legend.text=element_text(size=12), strip.text.x = element_text(size = 12), legend.title = element_text(size=12), legend.direction = "vertical", legend.position = "right", plot.title = element_text(hjust = 0.5)) +  labs(color=NULL)

ggsave(paste0("figures/predictions/SEAsia_pred_C580Y_pred", pred_year, "y.jpeg"), prev_c580y_plot, width = 8, height = 5, dpi=700)

ex <- pfk7_data %>% filter(is.finite(lrsmed_539t), nobs_r539t > numofobs, year >= min_year_r539t) %>% mutate(pt_color = case_when (year>min_year_r539t+ pred_year ~ "#55C667FF", year <= min_year_r539t+ pred_year ~ "#DCE319FF"))
df_pred <- df_predict %>% filter(District %in% unique(ex$District), year >= min_year +  pred_year)  
prev_r539t_plot <- 
  ggplot() +
  geom_line(data=ex %>% mutate(N = n+r539t), aes(year, predict_stan_prev_r539t, color = "true")) + 
  geom_line(data=df_pred %>% filter(Locus == "R539T"), aes(year, exp(predict)*100/(1+exp(predict)) , color = "predicted")) +
  geom_vline(data=ex, aes(xintercept= min_year_r539t+ pred_year), linetype = "dashed") +
  geom_point(data = ex, aes(x=year, y=prev_539t*100), color = ex$pt_color) +
  ggtitle("R539T") +
  labs(shape="Mutations", size = "Sample Size") +
  theme_bw() +
  facet_wrap(~country + District) +
  #scale_y_log10() +
  scale_color_manual(values=c("#440154FF", "#33638DFF")) + 
  #scale_fill_manual(values=c("grey", "#0072B2", "red", "green")) + 
  ylab("Prevalence") +
  xlab("Year") +
  ggpubr::theme_pubclean(base_size = 12) +
  theme(axis.line = element_line(), axis.text = element_text(size = 8), axis.title=element_text(size=12), legend.text=element_text(size=12), strip.text.x = element_text(size = 12), legend.title = element_text(size=12), legend.direction = "vertical", legend.position = "right", plot.title = element_text(hjust = 0.5)) +  labs(color=NULL)

ggsave(paste0("figures/predictions/SEAsia_pred_R539T_pred", pred_year, "y.jpeg"), prev_r539t_plot, width = 8, height = 5, dpi=700)

ex <- pfk7_data %>% filter(is.finite(lrsmed_all_kelch), nobs_kelch > numofobs, year >= min_year_all_kelch) %>% mutate(pt_color = case_when (year>min_year_all_kelch+ pred_year ~ "#55C667FF", year <= min_year_all_kelch+ pred_year ~ "#DCE319FF"))
df_pred <- df_predict %>% filter(District %in% unique(ex$District), year >= min_year +  pred_year)  
prev_all_kelch_plot <- 
  ggplot() +
  geom_line(data=ex %>% mutate(N = n+all_kelch), aes(year, predict_stan_prev_all_kelch, color = "true")) + 
  geom_line(data=df_pred %>% filter(Locus == "all_kelch"), aes(year, exp(predict)*100/(1+exp(predict)) , color = "predicted")) +
  geom_vline(data=ex, aes(xintercept= min_year_all_kelch+ pred_year), linetype = "dashed") +
  geom_point(data = ex, aes(x=year, y=prev_all_kelch*100), color = ex$pt_color) +
  ggtitle("PfK13") +
  labs(shape="Mutations", size = "Sample Size") +
  theme_bw() +
  facet_wrap(~country + District) +
  #scale_y_log10() +
  scale_color_manual(values=c("#440154FF", "#33638DFF")) + 
  #scale_fill_manual(values=c("grey", "#0072B2", "red", "green")) + 
  ylab("Prevalence") +
  xlab("Year") +
  ggpubr::theme_pubclean(base_size = 12) +
  theme(axis.line = element_line(), axis.text = element_text(size = 8), axis.title=element_text(size=12), legend.text=element_text(size=12), strip.text.x = element_text(size = 12), legend.title = element_text(size=12), legend.direction = "vertical", legend.position = "right", plot.title = element_text(hjust = 0.5)) +  labs(color=NULL)

ggsave(paste0("figures/predictions/SEAsia_pred_Pfk13_pred", pred_year, "y.jpeg"), prev_all_kelch_plot, width = 8, height = 5, dpi=700)
```

