---
title: "Kelch Uganda Prediction for 2,3,4 years"
output: html_document
date: "2023-04-26"
---

```{r setup, include=FALSE}
library(lme4)
library(nlme)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(scales)
library(tidyverse)
library(cowplot)
library(tabulizer)
library(RColorBrewer)
library(tidyverse) # ggplot2, dplyr, tidyr, readr, purrr, tibble
library(rnaturalearth)
library(rnaturalearthdata)
library(sf) #see ubuntu issues here: https://rtask.thinkr.fr/installation-of-r-4-0-on-ubuntu-20-04-lts-and-tips-for-spatial-packages/
library(ggspatial)
library(scatterpie)
library(scales)
library (ggforce)
library (ggmap)
library(rstan)
library(gt)
## install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))

```

# Load data
```{r}
#load data
df <- read.table("data/data-derived/Ugandan_data.txt")
df_comb <- read.table("data/data-derived/Ugandan_comb_data.txt")
#set the limit of number of observations
numofobs <- 2

fileLocManuscript <- "figures/"

df <- df %>%
  group_by(District, Locus) %>%
  mutate(min_year = min(year[x > 0])) %>%
  ungroup 
```

# Bayesian GMM with slopes and intercepts
```{r}
# ---- Model for Uganda (overall) -----
Uganda_stanmod <- rstanarm::stan_glmer(
  lrsmed ~ adj_year + (1 + adj_year | District),
  data = df_comb %>% filter(nobs > numofobs) %>% mutate(adj_year = year - 2016),
  weights = wt_med,
  adapt_delta = 0.9975
)

# ---- Model for c469y -----
c469y_stanmod <- rstanarm::stan_glmer(
  lrsmed ~ adj_year + (1 + adj_year | District),
  data = df %>% filter(Locus == "C469Y" &
                         nobs > numofobs) %>% mutate(adj_year = year - 2016),
  weights = wt_med,
  adapt_delta = 0.9975
)

vals <- summary(c469y_stanmod$stanfit)$summary[, 1]
vals <- vals[grep("^b", names(vals))]
ranef_c469y_stanmod <-
  data.frame("Intercepts" = vals[seq(1, length(vals), 2)],
             "Slopes" = vals[seq(2, length(vals), 2)])
ranef_c469y_stanmod$mutation <-
  rep("C469Y", dim(ranef_c469y_stanmod)[1])

# ---- Model for a675v -----
a675v_stanmod <- rstanarm::stan_glmer(
  lrsmed ~ adj_year + (1 + adj_year | District),
  data = df %>% filter(Locus == "A675V" &
                         nobs > numofobs) %>% mutate(adj_year = year - 2016),
  weights = wt_med,
  adapt_delta = 0.9975
)

vals <- summary(a675v_stanmod$stanfit)$summary[, 1]
vals <- vals[grep("^b", names(vals))]
ranef_a675v_stanmod <-
  data.frame("Intercepts" = vals[seq(1, length(vals), 2)],
             "Slopes" = vals[seq(2, length(vals), 2)])
ranef_a675v_stanmod$mutation <-
  rep("A675V", dim(ranef_a675v_stanmod)[1])

# ---- Model for c469f -----
c469f_stanmod <- rstanarm::stan_glmer(
  lrsmed ~ adj_year + (1 + adj_year | District),
  data = df %>% filter(Locus == "C469F" &
                         nobs > numofobs) %>% mutate(adj_year = year - 2016),
  weights = wt_med,
  adapt_delta = 0.9975
)

vals <- summary(c469f_stanmod$stanfit)$summary[, 1]
vals <- vals[grep("^b", names(vals))]
ranef_c469f_stanmod <-
  data.frame("Intercepts" = vals[seq(1, length(vals), 2)],
             "Slopes" = vals[seq(2, length(vals), 2)])
ranef_c469f_stanmod$mutation <-
  rep("C469F", dim(ranef_c469f_stanmod)[1])

# ---- combine selection coefficients -----
ranef_stanmod <-
  rbind(ranef_c469y_stanmod,
        ranef_a675v_stanmod,
        ranef_c469f_stanmod)
ranef_stanmod$site <-
  str_replace_all(rownames(ranef_stanmod), "\\[|\\]", "")
ranef_stanmod$site <-
  str_replace_all(ranef_stanmod$site, "\\s*\\([^\\)]+\\)", "")
ranef_stanmod$site <- str_remove(ranef_stanmod$site, "b District:")
ranef_stanmod$site <- str_remove(ranef_stanmod$site, "1")
```

## GMM posterior
```{r}
df$predict_stan <- NA
df_comb$predict_stan_Uganda <- NA

df_comb$predict_stan_Uganda[is.finite(df_comb$lrsmed) & df_comb$nobs > numofobs] <- rstanarm::posterior_predict(Uganda_stanmod, type = "response") %>% colMeans

df$predict_stan[is.finite(df$lrsmed) & df$Locus == "C469Y" & df$nobs > numofobs] <-  rstanarm::posterior_predict(c469y_stanmod, type = "response") %>% colMeans
df$predict_stan[is.finite(df$lrsmed) & df$Locus == "A675V" & df$nobs > numofobs] <-  rstanarm::posterior_predict(a675v_stanmod, type = "response") %>% colMeans
df$predict_stan[is.finite(df$lrsmed) & df$Locus == "C469F" & df$nobs > numofobs] <-  rstanarm::posterior_predict(c469f_stanmod, type = "response") %>% colMeans

```

## Obtain confidence interval of and posterior of posterior for each mutation
```{r}
#  get model predictions for plotting
df$conf.low <- NA
df$conf.high <- NA
df_comb$conf.low_uganda <- NA
df_comb$conf.high_uganda <- NA

c469y_conf <- rstanarm::posterior_predict(c469y_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))
c469f_conf <- rstanarm::posterior_predict(c469f_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))
a675v_conf <- rstanarm::posterior_predict(a675v_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))
uganda_ceof <- rstanarm::posterior_predict(Uganda_stanmod, type = "response") %>% apply(2, quantile, prob = (c(0.025, 0.975)))

# here just add predictions  for the c469Y rows
df$conf.low[is.finite(df$lrsmed) & df$Locus == "C469Y" & df$nobs > numofobs] <- c469y_conf[1,]
df$conf.low[is.finite(df$lrsmed) & df$Locus == "A675V" & df$nobs > numofobs] <- a675v_conf[1,]
df$conf.low[is.finite(df$lrsmed) & df$Locus == "C469F" & df$nobs > numofobs] <- c469f_conf[1,]
df_comb$conf.low_uganda[is.finite(df_comb$lrsmed) & df_comb$nobs > numofobs] <- uganda_ceof[1,]

df$conf.high[is.finite(df$lrsmed) & df$Locus == "C469Y" & df$nobs > numofobs] <- c469y_conf[2,]
df$conf.high[is.finite(df$lrsmed) & df$Locus == "A675V" & df$nobs > numofobs] <- a675v_conf[2,]
df$conf.high[is.finite(df$lrsmed) & df$Locus == "C469F" & df$nobs > numofobs] <- c469f_conf[2,]
df_comb$conf.high_uganda[is.finite(df_comb$lrsmed) & df_comb$nobs > numofobs] <- uganda_ceof[2,]
```

## Obtain GMM posterior for each mutation in prevalence scale
```{r}
df$predict_stan_prev <-
  exp(df$predict_stan) * 100 / (1 + exp(df$predict_stan))
df$conf.high_prev <- exp(df$conf.high) * 100 / (1 + exp(df$conf.high))
df$conf.low_prev <- exp(df$conf.low) * 100 / (1 + exp(df$conf.low))
```


# Forecasting Selection based on the first 2, 3, and 4 years
```{r}
pred_year <- c(2, 3, 4)

for (i in pred_year) {
  #------ Model prediction for C469Y ------
  c469y_pred <- rstanarm::stan_glmer(
    lrsmed ~ adj_year + (1 + adj_year | District),
    data = df %>% filter(
      Locus == "C469Y" &
        nobs > numofobs &
        year >= min_year &
        year <= min_year + i
    ) %>% mutate(adj_year = year - 2016),
    weights = wt_med,
    adapt_delta = 0.9975
  )
  
  # forecasting for C469Y
  new_data <- df %>%
    filter(nobs > numofobs, is.finite(df$lrsmed), Locus == "C469Y") %>% # this is for c469Y model
    group_by(District, Locus) %>% # we group by the District and Locus
    complete(year = seq(max(year), 2033, 1)) %>% # this creates all the year values up to 2023
    mutate(adj_year = year - 2016) %>%
    select(adj_year, year, District, Locus, min_year)
  
  new_data$predict <- rstanarm::posterior_predict(c469y_pred, type = "response", newdata = new_data) %>% colMeans
  conf_val <- rstanarm::posterior_predict(c469y_pred, type = "response", newdata = new_data) %>% 
    apply(2, quantile, prob = (c(0.025, 0.975)))
  new_data$conf.low <- conf_val[1,]
  new_data$conf.high <- conf_val[2,] 
  
  df_predict <- new_data
  
  #------ Model prediction for A675V ------
  a675v_pred <- rstanarm::stan_glmer(
    lrsmed ~ adj_year + (1 + adj_year | District),
    data = df %>% filter(
      Locus == "A675V" &
        nobs > numofobs &
        year >= min_year &
        year <= min_year +  i
    ) %>% mutate(adj_year = year - 2016),
    weights = wt_med,
    adapt_delta = 0.9975
  )
  
  # forecasting for A467V
  new_data <- df %>%
    filter(nobs > numofobs, is.finite(df$lrsmed), Locus == "A675V") %>% # this is for c469Y model
    group_by(District, Locus) %>% # we group by the District and Locus
    complete(year = seq(max(year), 2033, 1)) %>% # this creates all the year values up to 2023
    mutate(adj_year = year - 2016) %>%
    select(adj_year, year, District, Locus, min_year)
  
  new_data$predict <- rstanarm::posterior_predict(c469y_pred, type = "response", newdata = new_data) %>% colMeans
  conf_val <- rstanarm::posterior_predict(c469y_pred, type = "response", newdata = new_data) %>% 
    apply(2, quantile, prob = (c(0.025, 0.975)))
  new_data$conf.low <- conf_val[1,]
  new_data$conf.high <- conf_val[2,] 
  
  df_predict <- rbind(df_predict, new_data)
  
  
  #------ Model prediction for C469F ------
  c469f_pred <- rstanarm::stan_glmer(
    lrsmed ~ adj_year + (1 + adj_year | District),
    data = df %>% filter(
      Locus == "C469F" &
        nobs > numofobs &
        year >= min_year &
        year <= min_year +  i
    ) %>% mutate(adj_year = year - 2016),
    weights = wt_med,
    adapt_delta = 0.9975
  )
  
  
  # forecasting for C469F
  new_data <- df %>%
    filter(nobs > numofobs, is.finite(df$lrsmed), Locus == "C469F") %>% # this is for c469Y model
    group_by(District, Locus) %>% # we group by the District and Locus
    complete(year = seq(max(year), 2033, 1)) %>% # this creates all the year values up to 2023
    mutate(adj_year = year - 2016) %>%
    select(adj_year, year, District, Locus, min_year)
  
  new_data$predict <- rstanarm::posterior_predict(c469y_pred, type = "response", newdata = new_data) %>% colMeans
  conf_val <- rstanarm::posterior_predict(c469y_pred, type = "response", newdata = new_data) %>% 
    apply(2, quantile, prob = (c(0.025, 0.975)))
  new_data$conf.low <- conf_val[1,]
  new_data$conf.high <- conf_val[2,] 
  
  df_predict <- rbind(df_predict, new_data)
  
  df_predict <-
    df_predict %>% group_by(District, Locus) %>% mutate(min_year = replace_na(min_year, 0),
                                                        min_year = max(min_year)) %>% mutate(label = paste0(i, "year"),  pred_y = i)
  
  #Assigning df_predict to variables
  var_name <- paste0("df_predict_", i, "year")
  assign(var_name, df_predict)
}

#combine forecasting predictions for all years
df_predict_allyear <-
  rbind(df_predict_2year, df_predict_3year, df_predict_4year)
```

##Convert to prevalence
```{r}
df_predict_allyear <- df_predict_allyear %>% mutate(predict_prev = exp(predict)*100/(1+exp(predict)),
                                                    conf.low_prev = exp(conf.low)*100/(1+exp(conf.low)),
                                                    conf.high_prev = exp(conf.high)*100/(1+exp(conf.high)))
```

## Ploting forecasting of predictions for the first 2, 3, and 4 years
```{r}
################ PLOT FOR A675V ################
df_pred <- df_predict_allyear %>% 
  filter(Locus == "A675V", year >= min_year + pred_y)
ex <- df %>% 
  filter(is.finite(lrsmed), nobs > numofobs, Locus == "A675V", District %in% unique(df_pred$District))
ex_pt <- df %>% 
  filter(nobs > numofobs, Locus == "A675V", District %in% unique(df_pred$District)) %>%
   mutate(point_col = case_when(year >= min_year & year <= min_year + 2 ~ "#E69F00",
                               year > min_year + 2 & year <= min_year + 3 ~ "#56B4E9",
                               year > min_year + 3 & year <= min_year + 4 ~ "#0072B2",
                               year > min_year + 4 ~ "black",
                               year < min_year ~ "black")) 

pred_a675v <- ggplot() +
  geom_line(data = ex %>% mutate(N = n + x),
    aes(year, predict_stan_prev, color = "true"),
    linewidth = 1) +
  geom_line(data = df_pred, aes(year, predict_prev, group = label, color = label)) +
  geom_ribbon(data = df_pred, aes(ymin = conf.low_prev, ymax = conf.high_prev, x = year, group = label, color = label, fill = label), linetype = "dashed", alpha = 0.2,  show.legend = FALSE) +
  geom_point(data = ex_pt, aes(x = year, y = med * 100), color = ex_pt$point_col) +
  #ggtitle("A675V") +
  labs(shape="Mutations", size = "Sample Size") +
  theme_bw() +
  facet_wrap(~District) +
  ylab("Prevalence") +
  xlab("Year") +
  scale_color_manual(
    values = c("#E69F00", "#56B4E9", "#0072B2", "grey"),
    labels = c("2 years", "3 years", "4 years", "true")
  ) +
  scale_fill_manual(
    values = c("#E69F00", "#56B4E9", "#0072B2", "grey"),
    labels = c("2 years", "3 years", "4 years", "true")
  ) +
  ggpubr::theme_pubclean(base_size = 12) +
  theme(
    axis.line = element_line(),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 12),
    strip.text.x = element_text(size = 12),
    legend.title = element_text(size = 12),
    legend.direction = "vertical",
    legend.position = "right",
    plot.title = element_text(hjust = 0.5)
  ) +  labs(color = NULL)

################ PLOT FOR C469Y ################
df_pred <- df_predict_allyear %>% filter(Locus == "C469Y", year >= min_year + pred_y)
ex <-df %>% filter(is.finite(lrsmed), nobs > numofobs, Locus == "C469Y", District %in% unique(df_pred$District)) 
ex_pt <-df %>% 
  filter(nobs > numofobs, Locus == "C469Y", District %in% unique(df_pred$District)) %>%
   mutate(point_col = case_when(year >= min_year & year <= min_year + 2 ~ "#E69F00",
                               year > min_year + 2 & year <= min_year + 3 ~ "#56B4E9",
                               year > min_year + 3 & year <= min_year + 4 ~ "#0072B2",
                               year > min_year + 4 ~ "black",
                               year < min_year ~ "black")) 
pred_c469y <- ggplot() +
  geom_line(data = ex %>% mutate(N = n + x),
    aes(year, predict_stan_prev, color = "true"),
    linewidth = 1) +
  geom_line(data = df_pred, aes(year,predict_prev, group = label, color = label)) +
  geom_ribbon(data = df_pred, aes(ymin = conf.low_prev, ymax = conf.high_prev, x = year, group = label, color = label, fill = label), linetype = "dashed", alpha = 0.2,  show.legend = FALSE) +
  geom_point(data = ex_pt, aes(x = year, y = med * 100), color = ex_pt$point_col) +
  #ggtitle("C469Y") +
  labs(shape="Mutations", size = "Sample Size") +
  theme_bw() +
  facet_wrap(~District) +
  ylab("Prevalence") +
  xlab("Year") +
  scale_color_manual(
    values = c("#E69F00", "#56B4E9", "#0072B2", "grey"),
    labels = c("2 years", "3 years", "4 years", "true")
  ) +
  scale_fill_manual(
    values = c("#E69F00", "#56B4E9", "#0072B2", "grey"),
    labels = c("2 years", "3 years", "4 years", "true")
  ) +
  ggpubr::theme_pubclean(base_size = 12) +
  theme(
    axis.line = element_line(),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 10),
    legend.text = element_text(size = 10),
    strip.text.x = element_text(size = 10),
    legend.title = element_text(size = 10),
    legend.direction = "vertical",
    legend.position = "right",
    plot.title = element_text(hjust = 0.5)
  ) +  labs(color = NULL)

################ PLOT FOR C469F ################
df_pred <-df_predict_allyear %>% 
  filter(Locus == "C469F", year >= min_year + pred_y)
ex <-df %>% 
  filter(is.finite(lrsmed), nobs > numofobs, Locus == "C469F", District %in% unique(df_pred$District)) 
ex_pt <-df %>% 
  filter(nobs > numofobs, Locus == "C469F", District %in% unique(df_pred$District)) %>%
  mutate(point_col = case_when(year >= min_year & year <= min_year + 2 ~ "#E69F00",
                               year > min_year + 2 & year <= min_year + 3 ~ "#56B4E9",
                               year > min_year + 3 & year <= min_year + 4 ~ "#0072B2",
                               year > min_year + 4 ~ "black",
                               year < min_year ~ "black")) 

pred_c469f <- ggplot() +
  geom_line(data = ex %>% mutate(N = n + x),
    aes(year, predict_stan_prev, color = "true"),
    linewidth = 1
  ) +
  geom_line(data = df_pred, aes(year,predict_prev, group = label, color = label)) +
  geom_ribbon(data = df_pred, aes(ymin = conf.low_prev, ymax = conf.high_prev, x = year, group = label, color = label, fill = label), linetype = "dashed", alpha = 0.2,  show.legend = FALSE) +
  geom_point(data = ex_pt, aes(x = year, y = med * 100), color = ex_pt$point_col) +
  #ggtitle("C469F") +
  labs(shape="Mutations", size = "Sample Size") +
  theme_bw() +
  facet_wrap(~District) +
  ylab("Prevalence") +
  xlab("Year") +
  scale_color_manual(
    values = c("#E69F00", "#56B4E9", "#0072B2", "grey"),
    labels = c("2 years", "3 years", "4 years", "true")
  ) +
  scale_fill_manual(
    values = c("#E69F00", "#56B4E9", "#0072B2", "grey"),
    labels = c("2 years", "3 years", "4 years", "true")
  ) +
  ggpubr::theme_pubclean(base_size = 12) +
  theme(
    axis.line = element_line(),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 12),
    strip.text.x = element_text(size = 12),
    legend.title = element_text(size = 12),
    legend.direction = "vertical",
    legend.position = "right",
    plot.title = element_text(hjust = 0.5)
  ) +  labs(color = NULL)
```

## Saving plots
```{r}
ggsave(
  "figures/predictions/Uganda/Uganda_pred_A675V_pred.png",
  pred_a675v,
  width = 8,
  height = 5,
  dpi = 700
)
ggsave(
  "figures/predictions/Uganda/Uganda_pred_C469Y_pred.png",
  pred_c469y,
  width = 8,
  height = 5,
  dpi = 700
)
ggsave(
  "figures/predictions/Uganda/Uganda_pred_C469F_pred.png",
  pred_c469f,
  width = 8,
  height = 5,
  dpi = 700
)

ggsave(
  "figures/predictions/Uganda/Uganda_pred_A675V_pred.pdf",
  pred_a675v,
  width = 8,
  height = 5,
  dpi = 700
)
ggsave(
  "figures/predictions/Uganda/Uganda_pred_C469Y_pred.pdf",
  pred_c469y,
  width = 8,
  height = 5,
  dpi = 700
)
ggsave(
  "figures/predictions/Uganda/Uganda_pred_C469F_pred.pdf",
  pred_c469f,
  width = 8,
  height = 5,
  dpi = 700
)
```
