---
title: "Figure 1 - Kelch Selection Coefficient Modeling - MANUSCRIPT"
output: html_document
date: "2023-03-24"
---

```{r setup, include=FALSE}
library(lme4)
library(nlme)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(scales)
library(tidyverse)
library(cowplot)
library(tabulizer)
library(RColorBrewer)
library(tidyverse) # ggplot2, dplyr, tidyr, readr, purrr, tibble
library(rnaturalearth)
library(rnaturalearthdata)
library(sf) #see ubuntu issues here: https://rtask.thinkr.fr/installation-of-r-4-0-on-ubuntu-20-04-lts-and-tips-for-spatial-packages/
library(ggspatial)
library(scatterpie)
library(scales)
library (ggforce)
library (ggmap)
library(rstan)
library(gt)
## install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

#Load data
```{r}
#load data
df <- read.table("data/data-derived/Ugandan_data.txt")
df_comb <- read.table("data/data-derived/Ugandan_comb_data.txt")
#set the limit of number of observations
numofobs <- 2

fileLocManuscript <- "figures"
```

# Figure1A: Prevalence plot
```{r}
prev <- df %>% select(-x_org, -value) %>%
  rbind(df_comb %>% mutate(Locus = "PfK13 Mutation") %>% rename(x = comb)) %>%
  group_by(year, Locus) %>%
  mutate(all_genotyped = sum(n),
         mut_sample = sum(x),
         prev_sum = sum(med)) %>%
  ungroup %>%
  group_by(year) %>%
  mutate(n = length(unique(District)),
         all_genotyped = max(all_genotyped)) %>%
  select(Locus, year, adj_year, n, all_genotyped, mut_sample, prev_sum) %>%
  distinct(all_genotyped, mut_sample, prev_sum, .keep_all = TRUE) %>%
  mutate(prev_all = mut_sample/all_genotyped,
         prev_sum = prev_sum/n) %>%
  ungroup() %>%
  complete(year, Locus, fill = list(prev_all = 0)) %>%
  ggplot(aes(x = year, y = prev_all, fill=Locus, color = Locus)) +
  geom_bar(stat = "identity", position = position_dodge2(preserve = "single")) +
  theme_bw() +
  ylab("Prevalence") +
  scale_y_continuous(limits = c(0,0.3), 
                     labels = scales::percent) +
  scale_x_continuous("Year", 
                     labels = as.character(df$year), 
                     breaks = df$year) +
  scale_fill_manual(values = c("#D55E00",
                               "#0072B2",
                               "#009E73",
                               "#59386c",
                               "#BBBBBB",
                               "#F0E442"),
                    labels = c("675V",
                               "469F",
                               "469Y",
                               "441L",
                               "K13 combined",
                               "561H"),
                    name = "Mutations") +
  scale_color_manual(values = c("#D55E00",
                               "#0072B2",
                               "#009E73",
                               "#59386c",
                               "#BBBBBB",
                               "#F0E442"),
                    labels = c("675V",
                               "469F",
                               "469Y",
                               "441L",
                               "K13 combined",
                               "561H"),
                    name = "Mutations") +
  labs(fill='Mutations') +
  labs(fill='color') +
  theme(axis.text = element_text(size = 10), 
        axis.title=element_text(size=12), 
        legend.text=element_text(size=10), 
        strip.text.x = element_text(size = 10), 
        legend.position = c(.4 , .99), 
        legend.justification = c("right", "top"), 
        legend.box.just = "right", 
        legend.margin = margin(1, 1, 1, 1))
```

## Saving
```{r}
ggsave(
  paste0(
    fileLocManuscript,
    "/Figure1-UgandaPrevMap/Figure1A_Prevalence.pdf"
  ),
  prev,
  width = 4,
  height = 5.5,
  dpi = 700
)
ggsave(
  paste0(
    fileLocManuscript,
    "/Figure1-UgandaPrevMap/Figure1A_Prevalence.png"
  ),
  prev,
  width = 4,
  height = 5.5,
  dpi = 700
)

```

## Calculation
```{r}
prev_df <-  df %>% 
  group_by(year, Locus) %>% 
  mutate(min_n = sum(n), mut_sample = sum(x)) %>% 
  distinct(min_n, mut_sample) %>% 
  mutate(prop_sample = round((mut_sample/min_n)*100, 2))

avg_20162017 <- prev_df %>% 
  filter(year == 2016 || year == 2017) %>% 
  ungroup %>% 
  group_by(Locus) %>% 
  summarise(sum_prop_sample = mean(prop_sample))

avg_20202021 <- prev_df %>% 
  filter(year == 2020 || year == 2021) %>% 
  ungroup %>% group_by(Locus) %>% 
  summarise(sum_prop_sample = mean(prop_sample))

avg_2022 <- prev_df %>% 
  filter(year == 2022) %>% 
  ungroup %>% group_by(Locus) %>% 
  summarise(sum_prop_sample = prop_sample)

prev_comb_df <-  df_comb %>% 
  group_by(year) %>% 
  drop_na(comb) %>%
  mutate(min_n = sum(n), 
         mut_sample = sum(comb)) %>% 
  distinct(min_n, mut_sample) %>% 
  mutate(prop_sample = round((mut_sample/min_n)*100, 2))

max_med <- df %>%
  group_by(year) %>%
  drop_na(med) %>%
  mutate(med = med *100,
         max_district = District[which.max(med)],
         max_med = round(max(med, na.rm=TRUE),1)) %>%
  ungroup() %>%
  distinct(year, max_district, max_med)
  
```

# Figure1 B: Uganda Map
## Download and preprocessing for map of Uganda
```{r}
#load base map layers
admin8 <- ne_download(scale="large", type = "admin_1_states_provinces_lines",
                      category = "cultural", returnclass = "sf")
rivers8 <- ne_download(scale = 10, type = 'rivers_lake_centerlines',
                       category = 'physical', returnclass = "sf")
lakes8 <- ne_download(scale = "large", type = 'lakes',
                      category = 'physical', returnclass = "sf")
sov110 <- ne_download(scale="medium", type = "sovereignty",
                      category = "cultural", returnclass = "sf")
admin110 <- ne_download(scale="large", type = "populated_places",
                        category = "cultural", returnclass = "sf")
kampala <- data.frame(name="Kampala", long=32.5833, lat=0.31666)

pt.lim = data.frame(xlim = c(28.5, 35.5), ylim = c(4.25,-3))
pt.bbox <- st_bbox(c(xmin=pt.lim$xlim[1],
           xmax=pt.lim$xlim[2],
           ymin=pt.lim$ylim[1],
           ymax=pt.lim$ylim[2]))

uganda <- ne_states(country="Uganda", returnclass = "sf") %>% 
  st_crop(pt.bbox) %>% 
  select(name, latitude, longitude) %>%
  arrange(name)
uganda$name[uganda$name == "Kabale"] <- "Rukiga"
uganda <- uganda %>% 
  filter(name %in% unique(df$District)) %>% 
  na.omit() %>% 
  arrange(name) %>%
  filter(!name == "Amolatar")
```

## Per year checking
```{r}
#sum prevalence per Locus and District
pie_data <- df %>% 
  mutate(sum_district_locus = x) %>%
  select(year, District, Locus, sum_district_locus) %>% 
  distinct(District, Locus, year, .keep_all = TRUE) %>% 
  ungroup() 

#sum sample size for each District
all_genotyped <- df %>% 
  group_by(District, year) %>% 
  mutate(sum_district_locus = max(n)) %>% 
  select(year, District, sum_district_locus) %>% 
  distinct(District, year, .keep_all = TRUE) %>% 
  ungroup() 

#add all genotyped data to dataframe as additional rows
pie_data <- pie_data %>% 
  add_row(year = all_genotyped$year, 
          District = all_genotyped$District,
          Locus = rep("AllGenotyped", length(all_genotyped$District)), 
          sum_district_locus = all_genotyped$sum_district_locus) %>% 
  arrange(District) %>% 
  ungroup

#add long and lat to dataframe for plotting
pie_data$lat <- NA
pie_data$long <- NA
for (i in unique(uganda$name)){
  pie_data$lat[pie_data$District == i] <- rep(uganda$latitude[uganda$name == i], sum((pie_data$District == i)))
  pie_data$long[pie_data$District == i] <- rep(uganda$longitude[uganda$name == i], sum((pie_data$District == i)))
}

#initialize rows for each mutation and all genotyped
pie_data2 <- pie_data %>% select(year, District, lat, long) %>% distinct(year, District, .keep_all = TRUE)
pie_data2$A675V <- NA
pie_data2$C469Y <- NA
pie_data2$C469F <- NA
pie_data2$R561H <- NA
pie_data2$P441L <- NA
pie_data2$AllGenotyped <- NA

#obtain districts that obtain each mutation
C469Y_dist <- unique(df$District[df$Locus == "C469Y"])
A675V_dist <- unique(df$District[df$Locus == "A675V"])
C469F_dist <- unique(df$District[df$Locus == "C469F"])
R561H_dist <- unique(df$District[df$Locus == "R561H"])
P441L_dist <- unique(df$District[df$Locus == "P441L"])

#add prevalence for each mutation to dataframe
pie_data2$A675V[pie_data2$District %in% A675V_dist] <- pie_data$sum_district_locus[pie_data$Locus == "A675V"]
pie_data2$C469Y[pie_data2$District %in% C469Y_dist] <- pie_data$sum_district_locus[pie_data$Locus == "C469Y"]
pie_data2$C469F[pie_data2$District %in% C469F_dist] <- pie_data$sum_district_locus[pie_data$Locus == "C469F"]
pie_data2$R561H[pie_data2$District %in% R561H_dist] <- pie_data$sum_district_locus[pie_data$Locus == "R561H"]
pie_data2$P441L[pie_data2$District %in% P441L_dist] <- pie_data$sum_district_locus[pie_data$Locus == "P441L"]
pie_data2$AllGenotyped <- pie_data$sum_district_locus[pie_data$Locus == "AllGenotyped"]
pie_data2[is.na(pie_data2)] <- 0

pie_data2 <- pie_data2 %>%
  mutate(radius = (pie_data2$A675V + pie_data2$C469Y + pie_data2$C469F + pie_data2$R561H) / pie_data2$AllGenotyped) %>%
  filter(radius >0)

#rescale radius
minr<-min(pie_data2$radius)  # min in the data original scale
maxr<-max(pie_data2$radius)  # max in the data original scale
min_scale<-0.1  ## min in the new scale
max_scale<-0.45 ## max in the new scale
pie_data2$radius_adj <- min_scale + (max_scale-min_scale)*pie_data2$radius/(maxr-minr)
```

## Plotting for 2022
```{r}
# make plot with wild_type
pie_chart_df <- pie_data2 %>% filter(year == 2022)
map_uganda <- ggplot() +
  geom_sf(data=sov110, color='black', size=0.3, fill = ifelse(sov110$ADMIN == "Uganda", 'grey98', 'grey90')) +
  geom_sf(data=uganda, fill = "moccasin") +
  geom_sf(data=lakes8, color="grey40", fill ="aliceblue", size= 0.5) +
  geom_sf(data=admin8, color="grey80", size= 0.6) +
  geom_sf(data=admin110, color="grey80", size= 0.4) +
  annotation_scale(location = "bl", width_hint = 0.3, height = unit(0.1, "cm")) +
  annotation_north_arrow(location = "bl", which_north = "true",
                         pad_x = unit(0.25, "in"), pad_y = unit(0.15, "in"),
                         style = north_arrow_fancy_orienteering, height = unit(1, "cm"), width = unit(1, "cm")) +
  coord_sf(xlim = c(28.5, 35), ylim = c(4 ,-2), expand = TRUE) +
  annotate("text", x = 34.8, y = 0.5, label = "Kenya",
           color="grey50", size=4 , fontface="italic") +
  annotate("text", x = 29.4, y = 2, label = "Democratic Republic \n of the Congo",
           color="grey50", size=4 , fontface="italic") +
  annotate("text", x = 30.2, y = -1.9, label = "Rwanda",
           color="grey50", size=4 , fontface="italic") +
  annotate("text", x = 31.4, y = 3.956, label = "South Sudan",
           color="grey50", size=4 , fontface="italic") +
  annotate("text", x = 34.5, y = -2, label = "Tanzania",
           color="grey50", size=4 , fontface="italic") +
  theme_minimal() + 
  annotate(geom = "text", x = 31, y = -0.5, label = "Uganda", fontface = "bold", color = "black", size = 6) +
  annotate(geom = "text", x = 33, y = -1, label = "Lake Victoria", 
           fontface = "italic", color = "grey50", size = 5) +
  xlab("") +
  ylab("") +
  geom_scatterpie(data = pie_chart_df, 
                  aes(x=long, y=lat, group=District, r = radius_adj), 
                  cols=c("A675V", "C469F", "C469Y", "R561H", "P441L")) +
  geom_scatterpie_legend(pie_chart_df$radius_adj,
                         x=28.7,
                         y=0.7,
                         labeller = function(x) round(((0.639899*(x-0.1))/0.35)*100), #convert adjusted radius size back to the mutant/genotyped
                         n=4)+
    theme(legend.text=element_text(size=10), 
        axis.text = element_text(size = 10), 
        legend.position = c(0.085,0.84)) +
    scale_fill_manual(values = c("#D55E00",
                                 "#0072B2",
                                 "#009E73",
                                 "#F0E442",
                                 "#59386c"),
                      labels = c("675V",
                                 "469F",
                                 "469Y",
                                 "561H",
                                 "441L"),
                      name = "Mutations")


```

## Saving Plots
```{r}
ggsave(
  paste0(
    fileLocManuscript,
    paste0("/Figure1-UgandaPrevMap/Figure1B_MapUganda_2021.pdf")
  ),
  map_uganda,
  width = 6,
  height = 5.5,
  dpi = 700
  )
  ggsave(
    paste0(
      fileLocManuscript,
      paste0("/Figure1-UgandaPrevMap/Figure1B_MapUganda_2021.png")
    ),
    map_uganda,
    width = 6,
    height = 5.5,
    dpi = 700
  )

```
