---
title: "Supplement -Klech Selection Coefficient Modeling"
output: html_document
date: "2023-05-06"
---

```{r setup, include=FALSE}
library(lme4)
library(nlme)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(scales)
library(tidyverse)
library(cowplot)
library(tabulizer)
library(RColorBrewer)
library(tidyverse) # ggplot2, dplyr, tidyr, readr, purrr, tibble
library(rnaturalearth)
library(rnaturalearthdata)
library(sf) #see ubuntu issues here: https://rtask.thinkr.fr/installation-of-r-4-0-on-ubuntu-20-04-lts-and-tips-for-spatial-packages/
library(ggspatial)
library(scatterpie)
library(scales)
library (ggforce)
library (ggmap)
library(rstan)
library(gt)
library(ggbreak) 
## install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

# Load data
```{r}
#load data
df_uganda <- read.table("data/data-derived/Ugandan_data.txt")
df_pfk7 <- read.table("data/data-derived/NEW_pfk7_data.txt")
#set the limit of number of observations
numofobs <- 2

fileLocManuscript <- "figures/"
```

# Overview of data plot
## Uganda
```{r}
plot_overview_uganda <- df_uganda %>%
  mutate(N = n + x) %>%
  ggplot(aes(year, med * 100, group = Locus, color = Locus)) +
  geom_point() +
  labs(shape = "Mutations", size = "Sample Size") +
  theme_bw() +
  facet_wrap( ~ District) +
  ylab("Prevalence") +
  xlab("Year") +
  ylim(-1, 40) +
  scale_color_manual("Mutations",
    values = c("#D55E00", "#0072B2", "#009E73", "#F0E442"),
    labels = c("675V", "469F", "469Y", "561H")
  ) +
  ggpubr::theme_pubclean(base_size = 12) +
  theme(
    axis.line = element_line(),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 7),
    strip.text.x = element_text(size = 12),
    legend.title = element_text(size = 7),
    legend.position = c(0.94, 0.07),
    legend.box = "horizontal"
  )
```

### Saving plot
```{r}
ggsave(
  paste0(fileLocManuscript, "/supplement/Uganda_dataoverview.pdf"),
  plot_overview_uganda,
  width = 8,
  height = 5,
  dpi = 700
)
ggsave(
  paste0(fileLocManuscript, "/supplement/Uganda_dataoverview.png"),
  plot_overview_uganda,
  width = 8,
  height = 5,
  dpi = 700
)
```

## SE Asia (PfK7 data)
```{r}
plot_overview_seAsia <- df_pfk7 %>% filter(Locus != "other_PfK13") %>%
  mutate(N = n + x) %>%
  ggplot(aes(year, prev * 100, group = Locus, color = Locus)) +
  geom_point() +
  labs(shape = "Mutations", size = "Sample Size") +
  theme_bw() +
  facet_wrap( ~ country + District) +
  ylab("Prevalence") +
  xlab("Year") +
  scale_color_manual(values = c("#E69F00", "#56B4E9", "#009E73"), 
                     labels = c("PfK13", "580Y", "539T"),
                     name = "Mutations")  +
  ggpubr::theme_pubclean(base_size = 12) +
  theme(
    axis.line = element_line(),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 10),
    strip.text.x = element_text(size = 8),
    legend.title = element_text(size = 10),
    legend.position = "right",
    legend.box = "horizontal"
  )
```

### Saving plot
```{r}
ggsave(
  paste0(fileLocManuscript, "/supplement/SEAsia_dataoverview.pdf"),
  plot_overview_seAsia,
  width = 8,
  height = 10,
  dpi = 700
)
ggsave(
  paste0(fileLocManuscript, "/supplement/SEAsia_dataoverview.png"),
  plot_overview_seAsia,
  width = 8,
  height = 10,
  dpi = 700
)
```

# SE Asia
## Prevalence plot overview
```{r}
prev_df <- df_pfk7 %>% 
  group_by(year, Locus) %>% 
  filter(Locus != "PfK13") %>%
  mutate(n = sum(n), mut_sample = sum(x)) %>%
  distinct(n, mut_sample) %>%
  mutate(prop_sample = mut_sample / n) %>%
  ungroup

prev <- prev_df %>%
  ggplot(aes(x = year, y = prop_sample, fill = Locus)) +
  geom_col() +
  theme_bw() +
  scale_fill_manual("Mutations",
    values = c("#56B4E9", "#E69F00", "#009E73"),
    labels = c("580Y", "other PfK13", "539T")
  ) +
  xlab("Year") +
  ylab("Allele frequency") +
  ylim(0,1) +
  scale_x_continuous(breaks = seq(1993, 2018, 3)) +
  theme(
    legend.title = element_blank(),
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 10),
    strip.text.x = element_text(size = 10),
    legend.position = c(0.18, 0.9)
  )
```

### Saving plot
```{r}
ggsave(
  paste0(fileLocManuscript, "/supplement/SEAsia_prevalence.pdf"),
  prev,
  width = 4.5,
  height = 6.25,
  dpi = 700
)
ggsave(
  paste0(fileLocManuscript, "/supplement/SEAsia_prevalence.png"),
  prev,
  width = 4.5,
  height = 6.25,
  dpi = 700
)
```

## Map
### Download maps
```{r}
#load base map layers
admin8 <-
  ne_download(
    scale = "large",
    type = "admin_1_states_provinces_lines",
    category = "cultural",
    returnclass = "sf"
  )
rivers8 <- ne_download(
  scale = 10,
  type = 'rivers_lake_centerlines',
  category = 'physical',
  returnclass = "sf"
)
lakes8 <- ne_download(
  scale = "large",
  type = 'lakes',
  category = 'physical',
  returnclass = "sf"
)
sov110 <- ne_download(
  scale = "medium",
  type = "sovereignty",
  category = "cultural",
  returnclass = "sf"
)
admin110 <- ne_download(
  scale = "large",
  type = "populated_places",
  category = "cultural",
  returnclass = "sf"
)

pt.lim = data.frame(xlim = c(28.5, 35.5), ylim = c(4.25, -3))
pt.bbox <- st_bbox(c(
  xmin = pt.lim$xlim[1],
  xmax = pt.lim$xlim[2],
  ymin = pt.lim$ylim[1],
  ymax = pt.lim$ylim[2]
))
```

### Preprocessing
```{r}
#adjust names of Districts
SE_asia <-
  ne_states(country = unique(df_pfk7$country),
            returnclass = "sf") %>%
  #st_crop(pt.bbox) %>%
  select(name, admin, latitude, longitude) %>%
  arrange(name) %>% arrange(admin) %>%
  mutate(
    name = str_replace(name, "Batdâmbâng", "Battambang"),
    name = str_replace(name, "Kaôh Kong", "Koh Kong"),
    name = str_replace(name, "Krong Pailin", "Pailin"),
    name = str_replace(name, "Preah Vihéar", "Preah Vihear"),
    name = str_replace(name, "Pouthisat", "Pursat"),
    name = str_replace(name, "Si Sa Ket", "Sisakhet"),
    name = str_replace(name, "Rôtânôkiri", "Ratanakiri"),
    name = str_replace(name, "Attapu", "Attapeu"),
    name = str_replace(name, "Saravan", "Salavan"),
    name = str_replace(name, "Savannakhét", "Savannakhet"),
    name = str_replace(name, "Xékong", "Sekong"),
    name = str_replace(name, "Khánh Hòa", "Khanh Hoa"),
    name = str_replace(name, "Quàng Nam", "Quang Nam")
  )

#add Latitude for Districts that are not in the database
SE_asia$name[SE_asia$latitude == 9.33941] <- "Bac Lieu"
SE_asia$name[SE_asia$latitude == 11.6805] <- "Binh Phuoc"
SE_asia$name[SE_asia$latitude == 11.1284] <- "Binh Thuan"
SE_asia$name[SE_asia$latitude == 12.7691] <- "Dak Lak"
SE_asia$name[SE_asia$latitude == 12.1425] <- "Dak Nong"
SE_asia$name[SE_asia$latitude == 11.6242] <- "Ninh Thuan"
SE_asia$name[SE_asia$latitude == 16.7204] <- "Quang Tri"
SE_asia$name[SE_asia$latitude == 13.6662] <- "Stueng Traeng"

#filter districts that are in SE Asia
SE_asia <-
  SE_asia  %>% filter(name %in% unique(df_pfk7$District)) %>% na.omit() %>% arrange(name)

#adjust districts that contain non 
r539t_district <- df_pfk7 %>% 
  filter(Locus == "R539T", is.finite(lrsmed), nobs > numofobs) %>% 
  distinct(District)
r539t_district <- array(t(r539t_district))

c580y_district <- df_pfk7 %>% 
  filter(Locus == "C580Y", is.finite(lrsmed), nobs > numofobs) %>% 
  distinct(District)
c580y_district <- array(t(c580y_district))

allkelch_district <- df_pfk7 %>% 
  filter(Locus == "other_PfK13", is.finite(lrsmed), nobs > numofobs) %>% 
  distinct(District)
allkelch_district <- array(t(allkelch_district))

#label colors for map
SE_asia$color <- "not_enough_samples"
SE_asia$color[SE_asia$name %in% r539t_district] <- "r539t" #combined
SE_asia$color[SE_asia$name %in% c580y_district] <- "c580y" #combined
SE_asia$color[SE_asia$name %in% allkelch_district] <- "other PfK13" #only other kelch mutants

#sum prevalence per Locus and District
pie_data <- df_pfk7 %>% 
  group_by(Locus, District) %>% 
  mutate(sum_district_locus = sum(x)) %>% 
  filter(Locus != "PfK13") %>%
  select(District, Locus, sum_district_locus) %>% 
  distinct(District, Locus, .keep_all = TRUE) %>% 
  ungroup() 
#sum sample size for each District
nwild <- df_pfk7 %>% 
  group_by(District) %>% 
  mutate(sum_district_locus = sum(n)) %>% 
  select(District, sum_district_locus) %>% 
  distinct(District, .keep_all = TRUE) %>% 
  ungroup() 
#add wild-type to dataframe
pie_data <- pie_data %>% 
  add_row(District = unique(df_pfk7$District), Locus = rep("Wild-Type", dim(nwild)[1]), sum_district_locus = nwild$sum_district_locus) %>% 
  arrange(District) %>% 
  ungroup

#add long and lat to dataframe for plotting
pie_data$lat <- NA
pie_data$long <- NA
for (i in unique(pie_data$District)) {
  pie_data$lat[pie_data$District == i] <-
    rep(SE_asia$latitude[SE_asia$name == i], sum((pie_data$District == i)))
  pie_data$long[pie_data$District == i] <-
    rep(SE_asia$longitude[SE_asia$name == i], sum((pie_data$District == i)))
}

#initialize rows for each mutation and WT
pie_data2 <- pie_data %>% select(District, lat, long) %>% distinct(District, .keep_all = TRUE)
pie_data2$c580y <- NA
pie_data2$r539t <- NA
pie_data2$other_PfK13 <- NA
pie_data2$WildType <- NA

#obtain districts that obtain each mutation
C580Y_dist <- unique(df_pfk7$District[df_pfk7$Locus == "C580Y"])
R539T_dist <- unique(df_pfk7$District[df_pfk7$Locus == "R539T"])
other_PfK13_dist <- unique(df_pfk7$District[df_pfk7$Locus == "other_PfK13"])

#add prevalence for each mutation to dataframe
pie_data2$c580y[match(C580Y_dist, pie_data2$District)] <- pie_data$sum_district_locus[pie_data$Locus == "C580Y"]
pie_data2$r539t[match(R539T_dist, pie_data2$District)] <- pie_data$sum_district_locus[pie_data$Locus == "R539T"]
pie_data2$other_PfK13[match(other_PfK13_dist, pie_data2$District)] <- pie_data$sum_district_locus[pie_data$Locus == "other_PfK13"]
pie_data2$WildType <- pie_data$sum_district_locus[pie_data$Locus == "Wild-Type"]
pie_data2[is.na(pie_data2)] <- 0

pie_data2$radius <- (pie_data2$c580y + pie_data2$r539t + pie_data2$other_PfK13) / pie_data2$WildType
#rescale radius
minr <- min(pie_data2$radius)  # min in the data original scale
maxr <- max(pie_data2$radius)  # max in the data original scale

min_scale <- 0.3  ## min in the new scale
max_scale <- 0.7 ## max in the new scale

pie_data2$radius_adj <-
  min_scale + (max_scale - min_scale) * pie_data2$radius / (maxr - minr)
pie_data <- pie_data2
```

### Map with pie chart
```{r}
# make plot with wild_type
map_SEAsia <- ggplot() +
  geom_sf(
    data = sov110,
    color = 'black',
    size = 0.3,
    fill = ifelse(sov110$ADMIN %in% c("Laos", "Thailand", "Cambodia", "Vietnam", "Myanmar"), 'grey98', 'grey90')
  ) +
  geom_sf(data = SE_asia, fill = "moccasin") +
  geom_sf(
    data = lakes8,
    color = "grey40",
    fill = "aliceblue",
    size = 0.5
  ) +
  geom_sf(data = admin8, color = "grey80", size = 0.6) +
  geom_sf(data = admin110, color = "grey80", size = 0.4) +
  annotation_scale(
    location = "bl",
    width_hint = 0.3,
    height = unit(0.1, "cm")
  ) +
  annotation_north_arrow(
    location = "bl",
    which_north = "true",
    pad_x = unit(0.25, "in"),
    pad_y = unit(0.15, "in"),
    style = north_arrow_fancy_orienteering,
    height = unit(1, "cm"),
    width = unit(1, "cm")
  ) +
  coord_sf(xlim = c(109, 92.5),
           ylim = c(6.5, 28),
           expand = TRUE) +
  annotate(
    "text",
    x = 102.5,
    y = 20,
    label = "Laos",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 101.5,
    y = 16,
    label = "Thailand",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 105.9,
    y = 12.8,
    label = "Cambodia",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 104.9,
    y = 21.5,
    label = "Vietnam",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 95.2,
    y = 16.9,
    label = "Myanmar",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 102,
    y = 24,
    label = "China",
    color = "grey50",
    size = 4 ,
    fontface = "italic"
  ) +
  theme_minimal() +
  xlab("") +
  ylab("") +
  geom_scatterpie(
    data = pie_data,
    aes(
      x = long,
      y = lat,
      group = District,
      r = radius_adj
    ),
    cols = c("c580y", "r539t", "other_PfK13")
  ) +
  geom_scatterpie_legend(
    pie_data$radius_adj*2,
    x = 106,
    y = 24,
    labeller = function(x)
      round(100*(34*x/2 - 10.2))
  ) +
  scale_fill_manual(values = c("#56B4E9", "#009E73", "#E69F00"), labels = c("580Y", "539T", "other PfK13"), name = "")  +
  theme(
    legend.text = element_text(size = 10),
    axis.text = element_text(size = 10),
    legend.position = c(0.86, 0.95)
  )
```

#### Saving plot
```{r}
ggsave(
  paste0(
    fileLocManuscript,
    "/supplement/SEAsia_Map.pdf"
  ),
  map_SEAsia,
  width = 5.625,
  height = 6.25,
  dpi = 700
)
ggsave(
  paste0(
    fileLocManuscript,
    "/supplement/SEAsia_Map.png"
  ),
  map_SEAsia,
  width = 5.625,
  height = 6.25,
  dpi = 700
)
```


### Map of SE Asia
```{r}
# make plot with wild_type
map_SEAsia <- ggplot() +
  geom_sf(
    data = sov110,
    color = 'black',
    size = 0.3,
    fill = ifelse(
      sov110$ADMIN %in% c("Laos", "Thailand", "Cambodia", "Vietnam", "Myanmar"),
      'grey98',
      'grey90'
    )
  ) +
  geom_sf(data = SE_asia, aes(fill = color)) +
  geom_sf(
    data = lakes8,
    color = "grey40",
    fill = "aliceblue",
    size = 0.5
  ) +
  geom_sf(data = admin8, color = "grey80", size = 0.6) +
  geom_sf(data = admin110, color = "grey80", size = 0.4) +
  annotation_scale(
    location = "bl",
    width_hint = 0.3,
    height = unit(0.1, "cm")
  ) +
  annotation_north_arrow(
    location = "bl",
    which_north = "true",
    pad_x = unit(0.25, "in"),
    pad_y = unit(0.15, "in"),
    style = north_arrow_fancy_orienteering,
    height = unit(1, "cm"),
    width = unit(1, "cm")
  ) +
  coord_sf(xlim = c(109, 91),
           ylim = c(6.5, 28),
           expand = TRUE) +
  annotate(
    "text",
    x = 102.5,
    y = 20,
    label = "Laos",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 101.5,
    y = 16,
    label = "Thailand",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 105.9,
    y = 12.8,
    label = "Cambodia",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 104.9,
    y = 21.5,
    label = "Vietnam",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 95.2,
    y = 16.9,
    label = "Myanmar",
    color = "black",
    size = 3 ,
    fontface = "bold"
  ) +
  annotate(
    "text",
    x = 106,
    y = 24,
    label = "China",
    color = "grey50",
    size = 4 ,
    fontface = "italic"
  ) +
  theme_minimal() +
  xlab("") +
  ylab("") +
  #geom_scatterpie(data = pie_data, aes(x=long, y=lat, group=District, r = radius_adj), cols=c("c580y", "r539t", "all_kelch")) +
  #geom_scatterpie_legend(pie_data$radius*2, x=28.7, y=2.5, labeller = function(x) round(x * 100/2)) +
  scale_fill_manual(
    values = c("#56B4E9", "moccasin", "#E69F00", "#009E73"),
    labels = c("580Y", "not enough samples", "other PfK13", "539T"),
    name = ""
  )  +
  theme(
    legend.text = element_text(size = 10),
    axis.text = element_text(size = 10),
    legend.position = c(0.77, 0.90)
  )

```
